source 'https://rubygems.org'

gem 'rails', '4.0.0'
gem 'sass-rails', '~> 4.0.0'
gem 'haml', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'zurb-foundation'
gem 'jquery-rails'
gem 'jbuilder', '~> 1.2'
gem 'mongoid' , git: 'https://github.com/mongoid/mongoid.git'